[build]
builder = "DOCKERFILE"
dockerfilePath = "../../Dockerfile"
watchPatterns = ["/apps/web/**", "/packages/**"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
